name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Flet
      run: |
        pip install flet
        
    - name: Build APK
      run: |
        # We add 'flet' to the requirements right before building
        echo "flet" > requirements.txt
        flet build apk --verbose
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Titan-Calculator-v1
        path: build/apk/app-release.apk
