name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        pip install flet
        
    - name: Build APK
      run: |
        flet build apk --product "Titan Calc" --verbose
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Titan-Calculator-v1  # <--- THIS IS THE FILE NAME
        path: build/apk/app-release.apk
