name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2' # This is a very stable version for Flet
        channel: 'stable'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Flet
      run: pip install flet
        
    - name: Build APK
      run: |
        echo "flet" > requirements.txt
        # We add --no-interactive so it doesn't ask any questions
        flet build apk --verbose
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Titan-Calculator-v1
        path: build/apk/app-release.apk
